//! Maintain a managed block in `<project>/.gitignore` listing the symlinks
//! and copies agentenv currently owns.
//!
//! When [`crate::config::Config::gitignore_managed_links`] is `true`, the
//! sync engine calls [`refresh_managed_block`] after each successful sync to
//! rewrite a sentinel-delimited block in `.gitignore`. `agentenv clean`
//! calls [`remove_managed_block`] to strip the block entirely.
//!
//! User-authored `.gitignore` lines outside the block are preserved
//! verbatim — only the block contents change.

use crate::error::Result;
use crate::state::StateLink;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

/// Marker that opens the agentenv-managed block. Includes a hint not to
/// hand-edit and a pointer at the regenerating command.
pub const BEGIN_MARKER: &str =
    "# >>> agentenv managed (do not edit; regenerated by `agentenv sync`) <<<";

/// Marker that closes the agentenv-managed block.
pub const END_MARKER: &str = "# <<< agentenv managed >>>";

/// Standard filename agentenv writes to (project-root `.gitignore`).
const GITIGNORE_FILENAME: &str = ".gitignore";

/// Top-level directories that agentenv writes INTO but does not own
/// exclusively — collapsing to them would gitignore user-authored content
/// living alongside agentenv's. For these, the gitignore writer collapses
/// one level deeper (e.g. `.github/skills/x` → `/.github/skills/`, leaving
/// `.github/workflows/` and friends untouched).
const SHARED_NAMESPACES: &[&str] = &[".github"];

/// Refresh the managed block in `<project_root>/.gitignore` based on
/// `links` plus `extra_artifacts`.
///
/// Each managed path (a state-link target or a writer-supplied extra
/// artifact) is collapsed to its first project-relative path component:
/// `.cursor/skills/foo` → `/.cursor/`, `.cursor/hooks.json` → `/.cursor/`,
/// `AGENTS.md` → `/AGENTS.md`. The block thus ignores the whole tool folder
/// agentenv has written into, regardless of which capability landed there.
/// Entries are sorted alphabetically for stable diffs.
///
/// `extra_artifacts` exists for writers that materialize files outside the
/// state-link model (e.g. the hooks writers' `.cursor/hooks.json`).
///
/// If `.gitignore` doesn't exist, it's created with just the managed block.
/// If it exists but contains no markers, the block is appended at the end
/// (preceded by a blank line for readability if the existing file doesn't
/// already end with one). An empty block is still written when there's
/// nothing to track, so a future sync can splice into it.
pub fn refresh_managed_block(
    project_root: &Path,
    links: &[StateLink],
    extra_artifacts: &[PathBuf],
) -> Result<()> {
    let gitignore_path = project_root.join(GITIGNORE_FILENAME);
    let existing = read_existing(&gitignore_path)?;
    let entries = collect_entries(project_root, links, extra_artifacts);
    let new_block = render_block(&entries);
    let updated = splice_block(&existing, &new_block);
    write_atomically(&gitignore_path, &updated)
}

/// Remove the managed block from `<project_root>/.gitignore` entirely (both
/// the contents and the begin/end markers). User-authored lines outside the
/// block are preserved. Called by `agentenv clean`.
///
/// If `.gitignore` doesn't exist or contains no markers, this is a no-op.
pub fn remove_managed_block(project_root: &Path) -> Result<()> {
    let gitignore_path = project_root.join(GITIGNORE_FILENAME);
    let Some(existing) = read_existing(&gitignore_path)? else {
        return Ok(());
    };
    let updated = strip_block(&existing);
    if updated == existing {
        return Ok(()); // No markers present — nothing to remove.
    }
    write_atomically(&gitignore_path, &Some(updated))
}

fn read_existing(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(crate::error::Error::Io(err)),
    }
}

/// Build the sorted, deduplicated set of gitignore entries.
///
/// For each managed path (link target or extra artifact), strip the
/// project root and reduce to the first path component: a single-component
/// path is a project-root file (emit `/<name>`), anything deeper collapses
/// to its top-level folder (emit `/<first>/`). This is the "any folder
/// agentenv created" rule — it covers materialized files alongside
/// symlinks without listing each leaf separately.
///
/// Paths outside `project_root` are skipped defensively. Path separators
/// in the output are always `/`, even on Windows — git's `.gitignore`
/// format is platform-agnostic.
fn collect_entries(
    project_root: &Path,
    links: &[StateLink],
    extra_artifacts: &[PathBuf],
) -> Vec<String> {
    let mut set: BTreeSet<String> = BTreeSet::new();
    let mut push = |path: &Path| {
        let Ok(rel) = path.strip_prefix(project_root) else {
            return;
        };
        let components: Vec<String> = rel
            .components()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .collect();
        match components.as_slice() {
            [] => {},
            [only] => {
                set.insert(format!("/{only}"));
            },
            [first, second, ..] if SHARED_NAMESPACES.contains(&first.as_str()) => {
                // Shared parent (e.g. `.github/`): collapse one level deeper
                // so we don't ignore user-authored sibling content like
                // `.github/workflows/`.
                set.insert(format!("/{first}/{second}/"));
            },
            [first, ..] => {
                set.insert(format!("/{first}/"));
            },
        }
    };
    for link in links {
        push(&link.target);
    }
    for artifact in extra_artifacts {
        push(artifact);
    }
    set.into_iter().collect()
}

fn render_block(entries: &[String]) -> String {
    let mut out = String::new();
    out.push_str(BEGIN_MARKER);
    out.push('\n');
    for entry in entries {
        out.push_str(entry);
        out.push('\n');
    }
    out.push_str(END_MARKER);
    out
}

/// Splice the rendered block into `existing`. If a previous managed block
/// exists (begin/end markers present), replace its contents and markers
/// inclusively. Otherwise append at the end of the file (with a separating
/// blank line if needed).
fn splice_block(existing: &Option<String>, new_block: &str) -> Option<String> {
    let Some(existing) = existing else {
        // No file yet — start with the block followed by a trailing newline.
        let mut out = String::from(new_block);
        out.push('\n');
        return Some(out);
    };

    if let Some((begin_idx, end_idx)) = find_markers(existing) {
        let mut out = String::new();
        out.push_str(&existing[..begin_idx]);
        out.push_str(new_block);
        // `end_idx` points at END_MARKER; skip past it so the new_block's
        // own end marker isn't duplicated.
        out.push_str(&existing[end_idx + END_MARKER.len()..]);
        Some(out)
    } else {
        let mut out = existing.clone();
        // Ensure a separating blank line before the appended block.
        if !out.is_empty() && !out.ends_with("\n\n") {
            if out.ends_with('\n') {
                out.push('\n');
            } else {
                out.push_str("\n\n");
            }
        }
        out.push_str(new_block);
        out.push('\n');
        Some(out)
    }
}

/// Remove the markers and everything between them. If they aren't present,
/// returns `existing` unchanged.
fn strip_block(existing: &str) -> String {
    let Some((begin_idx, end_idx)) = find_markers(existing) else {
        return existing.to_string();
    };

    let mut out = String::new();
    out.push_str(&existing[..begin_idx]);
    // Skip the end-marker line + its newline if present.
    let after_end = existing[end_idx..]
        .strip_prefix(END_MARKER)
        .unwrap_or(&existing[end_idx..]);
    let after_end = after_end.strip_prefix('\n').unwrap_or(after_end);
    out.push_str(after_end);
    // Avoid leaving a trailing blank line we just created.
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// Returns `(byte_index_of_begin_marker, byte_index_of_end_marker)` if a
/// well-formed managed block exists in `existing`. The end index points at
/// the start of [`END_MARKER`] (caller is responsible for skipping past it
/// when splicing).
fn find_markers(existing: &str) -> Option<(usize, usize)> {
    let begin_idx = existing.find(BEGIN_MARKER)?;
    let end_search_start = begin_idx + BEGIN_MARKER.len();
    let relative_end = existing[end_search_start..].find(END_MARKER)?;
    let end_idx = end_search_start + relative_end;
    Some((begin_idx, end_idx))
}

/// Best-effort atomic write: write to `<path>.tmp` then rename. Avoids
/// leaving a half-written `.gitignore` if the process is killed mid-write.
fn write_atomically(path: &Path, content: &Option<String>) -> Result<()> {
    let Some(content) = content else {
        return Ok(());
    };
    let parent = path
        .parent()
        .ok_or_else(|| crate::error::Error::Config(format!("invalid path: {}", path.display())))?;
    let tmp = parent.join(format!(
        ".{}.tmp",
        path.file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_else(|| "gitignore".to_string())
    ));
    fs::write(&tmp, content)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn make_link(target: &str) -> StateLink {
        StateLink {
            source: PathBuf::from("/dummy/source"),
            target: PathBuf::from(target),
            tool: "test".to_string(),
            mode: "symlink".to_string(),
            plugin: "test-plugin".to_string(),
        }
    }

    #[test]
    fn creates_gitignore_when_absent() {
        let project = TempDir::new().unwrap();
        let link = make_link(
            project
                .path()
                .join(".cursor/agents/foo.md")
                .to_str()
                .unwrap(),
        );
        refresh_managed_block(project.path(), &[link], &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert!(content.contains(BEGIN_MARKER));
        // Collapsed to the top-level tool folder.
        assert!(content.contains("/.cursor/"));
        assert!(
            !content.contains("/.cursor/agents/foo.md"),
            "leaf path should be collapsed away"
        );
        assert!(content.contains(END_MARKER));
    }

    #[test]
    fn appends_block_when_gitignore_exists_without_markers() {
        let project = TempDir::new().unwrap();
        let path = project.path().join(".gitignore");
        fs::write(&path, "# user content\nnode_modules/\n").unwrap();
        let link = make_link(project.path().join(".junie/AGENTS.md").to_str().unwrap());
        refresh_managed_block(project.path(), &[link], &[]).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        // User content preserved.
        assert!(content.starts_with("# user content\nnode_modules/\n"));
        // Block appended; entry collapsed to `/.junie/`.
        assert!(content.contains(BEGIN_MARKER));
        assert!(content.contains("/.junie/"));
    }

    #[test]
    fn replaces_existing_managed_block_in_place() {
        let project = TempDir::new().unwrap();
        let path = project.path().join(".gitignore");
        // Seed with a user line, a managed block holding an old entry, and
        // a trailing user line. Replacement must keep both user lines.
        let initial = format!(
            "node_modules/\n\n{begin}\n/.cursor/agents/old.md\n{end}\n\n*.log\n",
            begin = BEGIN_MARKER,
            end = END_MARKER
        );
        fs::write(&path, &initial).unwrap();

        let link = make_link(
            project
                .path()
                .join(".cursor/agents/new.md")
                .to_str()
                .unwrap(),
        );
        refresh_managed_block(project.path(), &[link], &[]).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("node_modules/\n"));
        assert!(content.ends_with("*.log\n"));
        assert!(content.contains("/.cursor/"));
        assert!(
            !content.contains("/.cursor/agents/old.md"),
            "old leaf entry should be gone"
        );
        assert!(
            !content.contains("/.cursor/agents/new.md"),
            "new leaf entry should be collapsed to /.cursor/"
        );
    }

    #[test]
    fn refresh_is_idempotent() {
        let project = TempDir::new().unwrap();
        let link = make_link(project.path().join(".junie/AGENTS.md").to_str().unwrap());
        refresh_managed_block(project.path(), std::slice::from_ref(&link), &[]).unwrap();
        let first = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        refresh_managed_block(project.path(), std::slice::from_ref(&link), &[]).unwrap();
        let second = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert_eq!(
            first, second,
            "second refresh should produce identical file"
        );
    }

    #[test]
    fn entries_are_sorted_for_stable_diffs() {
        let project = TempDir::new().unwrap();
        let links = vec![
            make_link(project.path().join(".junie/AGENTS.md").to_str().unwrap()),
            make_link(
                project
                    .path()
                    .join(".cursor/agents/alpha.md")
                    .to_str()
                    .unwrap(),
            ),
            make_link(project.path().join(".cursor/skills/foo").to_str().unwrap()),
        ];
        refresh_managed_block(project.path(), &links, &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        // After collapsing, only two distinct entries remain (/.cursor/
        // and /.junie/), sorted alphabetically.
        let cursor_pos = content.find("/.cursor/").unwrap();
        let junie_pos = content.find("/.junie/").unwrap();
        assert!(cursor_pos < junie_pos);
    }

    #[test]
    fn collapses_multiple_leaves_under_same_folder_to_single_entry() {
        let project = TempDir::new().unwrap();
        let links = vec![
            make_link(project.path().join(".cursor/skills/a").to_str().unwrap()),
            make_link(project.path().join(".cursor/skills/b").to_str().unwrap()),
            make_link(project.path().join(".cursor/agents/c.md").to_str().unwrap()),
        ];
        refresh_managed_block(project.path(), &links, &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        // Exactly one `/.cursor/` line between the markers.
        let between = content
            .split(BEGIN_MARKER)
            .nth(1)
            .unwrap()
            .split(END_MARKER)
            .next()
            .unwrap();
        let cursor_lines = between.lines().filter(|l| l.contains(".cursor")).count();
        assert_eq!(
            cursor_lines, 1,
            "expected single /.cursor/ entry; got: {between}"
        );
    }

    #[test]
    fn shared_namespace_collapses_one_level_deeper() {
        // Copilot writes into `.github/` — a shared namespace that also
        // holds user-authored CI workflows, issue templates, etc. The
        // gitignore writer must collapse to `/.github/skills/` rather
        // than `/.github/` so siblings like `.github/workflows/ci.yml`
        // aren't accidentally ignored.
        let project = TempDir::new().unwrap();
        let links = vec![
            make_link(project.path().join(".github/skills/x").to_str().unwrap()),
            make_link(project.path().join(".github/agents/y.md").to_str().unwrap()),
        ];
        refresh_managed_block(project.path(), &links, &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert!(content.contains("/.github/skills/"));
        assert!(content.contains("/.github/agents/"));
        assert!(
            !content.lines().any(|l| l.trim() == "/.github/"),
            "must not emit a blanket /.github/ entry that would swallow workflows/"
        );
    }

    #[test]
    fn extra_artifact_covers_materialized_files_without_state_links() {
        // Cursor's hooks.json is materialized by the hooks writer and does
        // NOT appear in state.links. Passing it as an extra artifact must
        // still produce a `/.cursor/` ignore entry.
        let project = TempDir::new().unwrap();
        let hooks_path = project.path().join(".cursor/hooks.json");
        refresh_managed_block(project.path(), &[], &[hooks_path]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert!(content.contains("/.cursor/"));
    }

    #[test]
    fn root_level_files_emit_unsuffixed_entry() {
        // Instruction-file destinations like `AGENTS.md` live at the
        // project root and must stay file-shaped (no trailing slash).
        let project = TempDir::new().unwrap();
        let link = make_link(project.path().join("AGENTS.md").to_str().unwrap());
        refresh_managed_block(project.path(), &[link], &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert!(content.contains("\n/AGENTS.md\n"));
    }

    #[test]
    fn remove_block_strips_markers_and_contents() {
        let project = TempDir::new().unwrap();
        let path = project.path().join(".gitignore");
        let initial = format!(
            "node_modules/\n\n{begin}\n/.cursor/agents/foo.md\n{end}\n",
            begin = BEGIN_MARKER,
            end = END_MARKER
        );
        fs::write(&path, &initial).unwrap();

        remove_managed_block(project.path()).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(!content.contains(BEGIN_MARKER));
        assert!(!content.contains(END_MARKER));
        assert!(!content.contains(".cursor/agents/foo.md"));
        // User content survives.
        assert!(content.contains("node_modules/"));
    }

    #[test]
    fn remove_block_is_noop_when_no_markers() {
        let project = TempDir::new().unwrap();
        let path = project.path().join(".gitignore");
        let initial = "node_modules/\n";
        fs::write(&path, initial).unwrap();
        remove_managed_block(project.path()).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert_eq!(content, initial);
    }

    #[test]
    fn remove_block_is_noop_when_no_gitignore() {
        let project = TempDir::new().unwrap();
        remove_managed_block(project.path()).unwrap();
        assert!(!project.path().join(".gitignore").exists());
    }

    #[test]
    fn empty_links_writes_empty_block() {
        let project = TempDir::new().unwrap();
        refresh_managed_block(project.path(), &[], &[]).unwrap();
        let content = fs::read_to_string(project.path().join(".gitignore")).unwrap();
        assert!(content.contains(BEGIN_MARKER));
        assert!(content.contains(END_MARKER));
        // No entries — just the two markers (and the trailing newline).
        let between_markers = content
            .split(BEGIN_MARKER)
            .nth(1)
            .unwrap()
            .split(END_MARKER)
            .next()
            .unwrap();
        assert_eq!(between_markers.trim(), "");
    }
}
