//! Codex agent writer: render canonical agents as
//! `<project>/.codex/agents/<name>.toml`.
//!
//! Codex agents use a TOML schema, not Claude's Markdown+YAML frontmatter.
//! We translate only a documented subset of frontmatter keys and surface
//! the rest as drop warnings. The agent body becomes the `prompt` key.
//!
//! Each output file opens with a sentinel comment marking it as
//! agentenv-managed; subsequent syncs recognise that marker and freely
//! rewrite. A `.codex/agents/<name>.toml` file without the marker
//! triggers a refuse-on-conflict (matches the hooks codex writer at
//! [`crate::hooks::writers::codex`]).

use crate::agents::types::{Canonical, WriteReport};
use crate::agents::writers::{WriterOutcome, AGENTS_PLUGIN};
use crate::error::{Error, Result};
use crate::state::State;
use crate::state::StateLink;
use std::fs;
use std::path::{Path, PathBuf};

const SENTINEL: &str = "# >>> agentenv managed (do not edit; regenerated by `agentenv sync`) <<<";
const TARGET_DIR: &str = ".codex/agents";
const TARGET_NAME: &str = "codex";

/// Frontmatter keys we know how to translate to Codex TOML. Everything
/// else is dropped with a warning. Mirrors the documented Codex subagent
/// schema (docs link in `docs/platform-standards.md` §2).
const TRANSLATABLE_KEYS: &[&str] = &["name", "description", "model", "tools"];

/// Render every canonical agent to a managed TOML file.
pub fn write(
    canonical: &Canonical,
    project_root: &Path,
    _old_state: &State,
) -> Result<WriterOutcome> {
    let mut outcome = WriterOutcome::default();
    let dest_root = project_root.join(TARGET_DIR);

    for agent in &canonical.agents {
        // `source_file` is `#[serde(skip)]` — empty after deserializing from
        // disk. Production sync always re-runs the reader before this, so
        // we only hit this branch from callers that hand us a canonical
        // built without a reader (today: tests). Defensive guard.
        if agent.source_file.as_os_str().is_empty() {
            outcome.report.drops.push(format!(
                "codex: agent `{}` has no source_file captured — skipping",
                agent.name
            ));
            continue;
        }
        let dest = dest_root.join(format!("{}.toml", agent.name));
        detect_conflict(&dest)?;
        let toml = render(agent, &mut outcome.report);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&dest, toml)?;
        outcome.state_links.push(StateLink {
            // `source` records the canonical source file for traceability;
            // the actual content was rewritten so this is informational.
            source: agent.source_file.clone(),
            target: dest,
            tool: TARGET_NAME.to_string(),
            mode: "managed-file".to_string(),
            plugin: AGENTS_PLUGIN.to_string(),
        });
    }

    Ok(outcome)
}

/// Build the TOML body for one canonical agent.
///
/// Walks the translatable allow-list, drop-reports any other frontmatter
/// keys, and emits the body verbatim as the `prompt` field. We delegate
/// every escape decision to `toml::to_string_pretty` — hand-rolling
/// string escapes was bug-prone (bodies with `\`, trailing `"`, embedded
/// `"""` all corrupted on round-trip), and the `toml` crate handles all
/// of those correctly by construction.
fn render(agent: &crate::agents::types::CanonicalAgent, report: &mut WriteReport) -> String {
    let mut table = toml::map::Map::new();

    for key in TRANSLATABLE_KEYS {
        let key_val = serde_yaml::Value::String((*key).to_string());
        if let Some(v) = agent.frontmatter.get(&key_val) {
            match yaml_to_toml_value(v) {
                Some(toml_val) => {
                    table.insert((*key).to_string(), toml_val);
                },
                None => report.drops.push(format!(
                    "codex: dropping `{}.{key}` — value type cannot be expressed in TOML",
                    agent.name
                )),
            }
        }
    }

    for (k, _v) in &agent.frontmatter {
        let Some(key_str) = k.as_str() else {
            continue;
        };
        if TRANSLATABLE_KEYS.contains(&key_str) {
            continue;
        }
        report.drops.push(format!(
            "codex: dropping `{}.{key_str}` — not in the Codex TOML schema",
            agent.name
        ));
    }

    table.insert(
        "prompt".to_string(),
        toml::Value::String(agent.body.clone()),
    );

    // The table is built from in-memory primitives the toml crate accepts,
    // so serialization cannot fail at runtime.
    let body = toml::to_string_pretty(&toml::Value::Table(table))
        .expect("toml serialization of in-memory table cannot fail");
    let mut out = String::with_capacity(SENTINEL.len() + body.len() + 2);
    out.push_str(SENTINEL);
    out.push('\n');
    out.push_str(&body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Translate a YAML scalar (or homogeneous string array) into the
/// matching `toml::Value`. Returns `None` for nested mappings, mixed-type
/// arrays, or other shapes the documented Codex schema doesn't accept —
/// caller turns that into a drop warning.
fn yaml_to_toml_value(v: &serde_yaml::Value) -> Option<toml::Value> {
    match v {
        serde_yaml::Value::String(s) => Some(toml::Value::String(s.clone())),
        serde_yaml::Value::Bool(b) => Some(toml::Value::Boolean(*b)),
        serde_yaml::Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                Some(toml::Value::Integer(i))
            } else {
                n.as_f64().map(toml::Value::Float)
            }
        },
        serde_yaml::Value::Sequence(items) => {
            let mut out = Vec::with_capacity(items.len());
            for item in items {
                let serde_yaml::Value::String(s) = item else {
                    return None;
                };
                out.push(toml::Value::String(s.clone()));
            }
            Some(toml::Value::Array(out))
        },
        _ => None,
    }
}

/// Refuse to overwrite if the destination exists without the sentinel
/// header — same conservative stance as the hooks codex writer.
fn detect_conflict(dest: &PathBuf) -> Result<()> {
    if !dest.exists() {
        return Ok(());
    }
    let raw = fs::read_to_string(dest)?;
    if raw.trim_start().starts_with(SENTINEL) {
        return Ok(());
    }
    Err(Error::Config(format!(
        "{} exists but is not an agentenv-managed agent file (missing sentinel comment). \
         Remove or move it before re-syncing.",
        dest.display()
    )))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agents::types::CanonicalAgent;
    use tempfile::TempDir;

    fn agent_with_frontmatter(
        name: &str,
        fm_yaml: &str,
        body: &str,
        source: &Path,
    ) -> CanonicalAgent {
        let value: serde_yaml::Value = serde_yaml::from_str(fm_yaml).unwrap();
        let frontmatter = match value {
            serde_yaml::Value::Mapping(m) => m,
            _ => serde_yaml::Mapping::new(),
        };
        CanonicalAgent {
            name: name.to_string(),
            frontmatter,
            body: body.to_string(),
            source_file: source.to_path_buf(),
        }
    }

    fn touch(path: &Path) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, "src").unwrap();
    }

    #[test]
    fn writes_known_keys_and_prompt_body() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: Reviews PRs\nmodel: gpt-5\ntools: [Read, Grep]",
            "You are a reviewer.\nLine 2.\n",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert!(
            outcome.report.drops.is_empty(),
            "drops: {:?}",
            outcome.report.drops
        );
        assert_eq!(outcome.state_links.len(), 1);

        let dest = project.path().join(".codex/agents/rev.toml");
        let raw = fs::read_to_string(&dest).unwrap();
        assert!(raw.starts_with(SENTINEL));

        // Behavior — not implementation: the TOML must parse back and
        // every field must round-trip with the value we asked to render.
        // The exact escape form (basic vs. multi-line, inline vs. wrapped
        // array) is left to `toml::to_string_pretty`.
        let parsed: toml::Value = toml::from_str(&raw).unwrap();
        assert_eq!(parsed["name"].as_str(), Some("rev"));
        assert_eq!(parsed["description"].as_str(), Some("Reviews PRs"));
        assert_eq!(parsed["model"].as_str(), Some("gpt-5"));
        let tools: Vec<&str> = parsed["tools"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        assert_eq!(tools, vec!["Read", "Grep"]);
        assert_eq!(
            parsed["prompt"].as_str().unwrap(),
            "You are a reviewer.\nLine 2.\n"
        );
    }

    #[test]
    fn drops_unknown_frontmatter_keys_with_warning() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: r\npermissionMode: readonly\nmcpServers: [github]\nhooks: {PreToolUse: x}",
            "body",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        let drop_text = outcome.report.drops.join("\n");
        assert!(drop_text.contains("permissionMode"), "drops: {drop_text}");
        assert!(drop_text.contains("mcpServers"), "drops: {drop_text}");
        assert!(drop_text.contains("hooks"), "drops: {drop_text}");
        let raw = fs::read_to_string(project.path().join(".codex/agents/rev.toml")).unwrap();
        assert!(!raw.contains("permissionMode"));
        assert!(!raw.contains("mcpServers"));
    }

    #[test]
    fn idempotent_overwrites_own_output() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter("rev", "name: rev\ndescription: r", "body", &src);
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        write(&canonical, project.path(), &State::default()).unwrap();
        // Second write must succeed — sentinel recognises our own output.
        write(&canonical, project.path(), &State::default()).unwrap();
    }

    #[test]
    fn refuses_user_authored_file() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let dest = project.path().join(".codex/agents/rev.toml");
        fs::create_dir_all(dest.parent().unwrap()).unwrap();
        fs::write(&dest, "name = \"user\"\nprompt = \"mine\"\n").unwrap();

        let agent = agent_with_frontmatter("rev", "name: rev\ndescription: r", "body", &src);
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let err = write(&canonical, project.path(), &State::default()).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("not an agentenv-managed"), "got: {msg}");
        // User file preserved verbatim.
        assert_eq!(
            fs::read_to_string(&dest).unwrap(),
            "name = \"user\"\nprompt = \"mine\"\n"
        );
    }

    #[test]
    fn drops_unsupported_value_types() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        // `tools` here is a mixed-type array — not expressible in our
        // documented schema. Must be dropped with a warning.
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: r\ntools: [Read, 42]",
            "body",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert!(
            outcome.report.drops.iter().any(|w| w.contains("tools")),
            "drops: {:?}",
            outcome.report.drops
        );
        let raw = fs::read_to_string(project.path().join(".codex/agents/rev.toml")).unwrap();
        // `tools` line should not have made it through.
        assert!(!raw.contains("tools = "), "got: {raw}");
    }

    /// Round-trip the body of an agent through render → parse and assert
    /// the parsed `prompt` value equals the original byte-for-byte.
    /// Used by every "body content is preserved" test below.
    fn assert_prompt_round_trips(body: &str) {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter("rev", "name: rev\ndescription: r", body, &src);
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        write(&canonical, project.path(), &State::default()).unwrap();
        let raw = fs::read_to_string(project.path().join(".codex/agents/rev.toml")).unwrap();
        let parsed: toml::Value = toml::from_str(&raw).expect("rendered output must parse as TOML");
        assert_eq!(
            parsed["prompt"].as_str().unwrap(),
            body,
            "prompt round-trip mismatch — render+parse must yield the original body"
        );
    }

    #[test]
    fn body_with_backslash_round_trips() {
        // The old hand-rolled triple-quoted writer used TOML basic
        // strings, which treat `\` as an escape — bodies containing
        // literal `\n`, `\\`, or Windows paths would get silently
        // mangled on the round-trip.
        assert_prompt_round_trips("line with literal backslash-n: \\n end\n");
        assert_prompt_round_trips("double backslash: \\\\ end\n");
    }

    #[test]
    fn body_ending_in_double_quote_round_trips() {
        // Bodies ending in `"` would butt up against the closing `"""`
        // delimiter under the old writer and produce ambiguous or
        // invalid TOML. `toml::to_string_pretty` handles this case.
        assert_prompt_round_trips("he said \"hello\"");
        assert_prompt_round_trips("ends with two quotes: \"\"");
    }

    #[test]
    fn body_containing_triple_quote_round_trips() {
        // Embedded `"""` in the body would prematurely close the old
        // writer's delimited string. Must survive intact now.
        assert_prompt_round_trips("before \"\"\" after\n");
    }

    #[test]
    fn body_with_windows_path_round_trips() {
        // Common real-world content: Windows path. The old writer's
        // un-escaped `\U` would get interpreted as a TOML unicode escape.
        assert_prompt_round_trips("path: C:\\Users\\foo\\bar.txt\n");
    }

    #[test]
    fn empty_source_file_is_skipped_with_warning() {
        let project = TempDir::new().unwrap();
        let mut agent = agent_with_frontmatter(
            "ghost",
            "name: ghost\ndescription: r",
            "",
            project.path(), // tmp; we overwrite source_file below
        );
        agent.source_file = PathBuf::new();
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert_eq!(outcome.state_links.len(), 0);
        assert!(outcome.report.drops[0].contains("ghost"));
    }
}
