//! Codex agent writer: render canonical agents as
//! `<project>/.codex/agents/<name>.toml`.
//!
//! Codex agents use a TOML schema, not Claude's Markdown+YAML frontmatter.
//! We translate only a documented subset of frontmatter keys and surface
//! the rest as drop warnings. The agent body becomes the `prompt` key.
//!
//! Each output file opens with a sentinel comment marking it as
//! agentenv-managed; subsequent syncs recognise that marker and freely
//! rewrite. A `.codex/agents/<name>.toml` file without the marker
//! triggers a refuse-on-conflict (matches the hooks codex writer at
//! [`crate::hooks::writers::codex`]).

use crate::agents::types::{Canonical, WriteReport};
use crate::agents::writers::{WriterOutcome, AGENTS_PLUGIN};
use crate::error::{Error, Result};
use crate::state::State;
use crate::state::StateLink;
use std::fs;
use std::path::{Path, PathBuf};

const SENTINEL: &str = "# >>> agentenv managed (do not edit; regenerated by `agentenv sync`) <<<";
const TARGET_DIR: &str = ".codex/agents";
const TARGET_NAME: &str = "codex";

/// Frontmatter keys we know how to translate to Codex TOML. Everything
/// else is dropped with a warning. Mirrors the documented Codex subagent
/// schema (docs link in `docs/platform-standards.md` §2).
const TRANSLATABLE_KEYS: &[&str] = &["name", "description", "model", "tools"];

/// Render every canonical agent to a managed TOML file.
pub fn write(
    canonical: &Canonical,
    project_root: &Path,
    _old_state: &State,
) -> Result<WriterOutcome> {
    let mut outcome = WriterOutcome::default();
    let dest_root = project_root.join(TARGET_DIR);

    for agent in &canonical.agents {
        if agent.source_file.as_os_str().is_empty() {
            outcome.report.drops.push(format!(
                "codex: agent `{}` has no source_file captured — skipping",
                agent.name
            ));
            continue;
        }
        let dest = dest_root.join(format!("{}.toml", agent.name));
        detect_conflict(&dest)?;
        let toml = render(agent, &mut outcome.report);
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&dest, toml)?;
        outcome.state_links.push(StateLink {
            // `source` records the canonical source file for traceability;
            // the actual content was rewritten so this is informational.
            source: agent.source_file.clone(),
            target: dest,
            tool: TARGET_NAME.to_string(),
            mode: "managed-file".to_string(),
            plugin: AGENTS_PLUGIN.to_string(),
        });
    }

    Ok(outcome)
}

/// Build the TOML body for one canonical agent. Walks frontmatter once,
/// emitting documented keys and pushing drop reasons for the rest. Body
/// becomes `prompt = """…"""`.
fn render(agent: &crate::agents::types::CanonicalAgent, report: &mut WriteReport) -> String {
    use std::fmt::Write as _;

    let mut out = String::new();
    writeln!(out, "{SENTINEL}").unwrap();

    for key in TRANSLATABLE_KEYS {
        let key_val = serde_yaml::Value::String((*key).to_string());
        if let Some(v) = agent.frontmatter.get(&key_val) {
            if let Some(rendered) = yaml_to_toml_scalar_or_array(v) {
                writeln!(out, "{key} = {rendered}").unwrap();
            } else {
                report.drops.push(format!(
                    "codex: dropping `{}.{key}` — value type cannot be expressed in TOML",
                    agent.name
                ));
            }
        }
    }

    for (k, _v) in &agent.frontmatter {
        let Some(key_str) = k.as_str() else {
            continue;
        };
        if TRANSLATABLE_KEYS.contains(&key_str) {
            continue;
        }
        report.drops.push(format!(
            "codex: dropping `{}.{key_str}` — not in the Codex TOML schema",
            agent.name
        ));
    }

    writeln!(out).unwrap();
    write!(out, "prompt = {}", literal_string(&agent.body)).unwrap();
    out.push('\n');
    out
}

/// Render a YAML scalar (or homogeneous string array) as a TOML value
/// literal. Returns `None` for nested mappings, mixed-type arrays, or
/// other shapes the documented Codex schema doesn't accept.
fn yaml_to_toml_scalar_or_array(v: &serde_yaml::Value) -> Option<String> {
    match v {
        serde_yaml::Value::String(s) => Some(toml_string_literal(s)),
        serde_yaml::Value::Bool(b) => Some(b.to_string()),
        serde_yaml::Value::Number(n) => Some(n.to_string()),
        serde_yaml::Value::Sequence(items) => {
            let mut parts = Vec::with_capacity(items.len());
            for item in items {
                let serde_yaml::Value::String(s) = item else {
                    return None;
                };
                parts.push(toml_string_literal(s));
            }
            Some(format!("[{}]", parts.join(", ")))
        },
        _ => None,
    }
}

/// Inline TOML string literal — uses basic double-quoted form with simple
/// escapes. Multi-line bodies use [`literal_string`] instead.
fn toml_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Multi-line TOML literal — triple-quoted to preserve the body verbatim.
/// Escapes any embedded `"""` to keep the file parseable.
fn literal_string(body: &str) -> String {
    let safe = body.replace("\"\"\"", "\"\"\\\"");
    format!("\"\"\"\n{safe}\"\"\"")
}

/// Refuse to overwrite if the destination exists without the sentinel
/// header — same conservative stance as the hooks codex writer.
fn detect_conflict(dest: &PathBuf) -> Result<()> {
    if !dest.exists() {
        return Ok(());
    }
    let raw = fs::read_to_string(dest)?;
    if raw.trim_start().starts_with(SENTINEL) {
        return Ok(());
    }
    Err(Error::Config(format!(
        "{} exists but is not an agentenv-managed agent file (missing sentinel comment). \
         Remove or move it before re-syncing.",
        dest.display()
    )))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agents::types::CanonicalAgent;
    use tempfile::TempDir;

    fn agent_with_frontmatter(
        name: &str,
        fm_yaml: &str,
        body: &str,
        source: &Path,
    ) -> CanonicalAgent {
        let value: serde_yaml::Value = serde_yaml::from_str(fm_yaml).unwrap();
        let frontmatter = match value {
            serde_yaml::Value::Mapping(m) => m,
            _ => serde_yaml::Mapping::new(),
        };
        CanonicalAgent {
            name: name.to_string(),
            frontmatter,
            body: body.to_string(),
            source_file: source.to_path_buf(),
        }
    }

    fn touch(path: &Path) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, "src").unwrap();
    }

    #[test]
    fn writes_known_keys_and_prompt_body() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: Reviews PRs\nmodel: gpt-5\ntools: [Read, Grep]",
            "You are a reviewer.\nLine 2.\n",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert!(
            outcome.report.drops.is_empty(),
            "drops: {:?}",
            outcome.report.drops
        );
        assert_eq!(outcome.state_links.len(), 1);

        let dest = project.path().join(".codex/agents/rev.toml");
        let raw = fs::read_to_string(&dest).unwrap();
        assert!(raw.starts_with(SENTINEL));
        assert!(raw.contains("name = \"rev\""));
        assert!(raw.contains("description = \"Reviews PRs\""));
        assert!(raw.contains("model = \"gpt-5\""));
        assert!(raw.contains("tools = [\"Read\", \"Grep\"]"));
        assert!(raw.contains("prompt = \"\"\""));
        assert!(raw.contains("You are a reviewer."));

        // Parses as valid TOML.
        let parsed: toml::Value = toml::from_str(&raw).unwrap();
        assert_eq!(parsed["name"].as_str(), Some("rev"));
        assert_eq!(
            parsed["prompt"].as_str().unwrap().trim(),
            "You are a reviewer.\nLine 2."
        );
    }

    #[test]
    fn drops_unknown_frontmatter_keys_with_warning() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: r\npermissionMode: readonly\nmcpServers: [github]\nhooks: {PreToolUse: x}",
            "body",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        let drop_text = outcome.report.drops.join("\n");
        assert!(drop_text.contains("permissionMode"), "drops: {drop_text}");
        assert!(drop_text.contains("mcpServers"), "drops: {drop_text}");
        assert!(drop_text.contains("hooks"), "drops: {drop_text}");
        let raw = fs::read_to_string(project.path().join(".codex/agents/rev.toml")).unwrap();
        assert!(!raw.contains("permissionMode"));
        assert!(!raw.contains("mcpServers"));
    }

    #[test]
    fn idempotent_overwrites_own_output() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let agent = agent_with_frontmatter("rev", "name: rev\ndescription: r", "body", &src);
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        write(&canonical, project.path(), &State::default()).unwrap();
        // Second write must succeed — sentinel recognises our own output.
        write(&canonical, project.path(), &State::default()).unwrap();
    }

    #[test]
    fn refuses_user_authored_file() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        let dest = project.path().join(".codex/agents/rev.toml");
        fs::create_dir_all(dest.parent().unwrap()).unwrap();
        fs::write(&dest, "name = \"user\"\nprompt = \"mine\"\n").unwrap();

        let agent = agent_with_frontmatter("rev", "name: rev\ndescription: r", "body", &src);
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let err = write(&canonical, project.path(), &State::default()).unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("not an agentenv-managed"), "got: {msg}");
        // User file preserved verbatim.
        assert_eq!(
            fs::read_to_string(&dest).unwrap(),
            "name = \"user\"\nprompt = \"mine\"\n"
        );
    }

    #[test]
    fn drops_unsupported_value_types() {
        let project = TempDir::new().unwrap();
        let src = project.path().join(".claude/agents/rev.md");
        touch(&src);
        // `tools` here is a mixed-type array — not expressible in our
        // documented schema. Must be dropped with a warning.
        let agent = agent_with_frontmatter(
            "rev",
            "name: rev\ndescription: r\ntools: [Read, 42]",
            "body",
            &src,
        );
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert!(
            outcome.report.drops.iter().any(|w| w.contains("tools")),
            "drops: {:?}",
            outcome.report.drops
        );
        let raw = fs::read_to_string(project.path().join(".codex/agents/rev.toml")).unwrap();
        // `tools` line should not have made it through.
        assert!(!raw.contains("tools = "), "got: {raw}");
    }

    #[test]
    fn empty_source_file_is_skipped_with_warning() {
        let project = TempDir::new().unwrap();
        let mut agent = agent_with_frontmatter(
            "ghost",
            "name: ghost\ndescription: r",
            "",
            project.path(), // tmp; we overwrite source_file below
        );
        agent.source_file = PathBuf::new();
        let canonical = Canonical {
            source: "claude-code".to_string(),
            agents: vec![agent],
        };
        let outcome = write(&canonical, project.path(), &State::default()).unwrap();
        assert_eq!(outcome.state_links.len(), 0);
        assert!(outcome.report.drops[0].contains("ghost"));
    }
}
