//! Codex writer: emit a `notify = [...]` line in `~/.codex/config.toml`.
//!
//! Codex only exposes a single turn-end hook (`notify`), so only canonical
//! `Stop` events materialize here. Everything else is dropped with a
//! [`WriteReport`] entry.
//!
//! `~/.codex/config.toml` is user-global and typically holds unrelated
//! settings (auth, MCP servers, model preferences). agentenv preserves all
//! that by managing only a sentinel-delimited block of TOML inside the
//! file. If a `notify = ...` line exists outside that block — meaning the
//! user (or another tool) authored their own — the writer refuses to
//! overwrite.
//!
//! When there is at least one `Stop` hook, the writer also emits a tiny
//! dispatcher shell script at
//! `<project_root>/.agentenv/hooks/codex-notify-dispatch.sh` that fans out
//! Codex's single notify payload across every Stop hook.

use crate::error::{Error, Result};
use crate::hooks::types::{Action, Canonical, CommonEvent, Event, WriteReport};
use crate::state::STATE_DIR;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

/// Sentinel that opens the agentenv-managed block in `config.toml`.
pub const BEGIN_MARKER: &str =
    "# >>> agentenv managed (do not edit; regenerated by `agentenv sync`) <<<";
/// Sentinel that closes the agentenv-managed block in `config.toml`.
pub const END_MARKER: &str = "# <<< agentenv managed >>>";

const DISPATCHER_DIR: &str = "hooks";
const DISPATCHER_FILE: &str = "codex-notify-dispatch.sh";

/// Absolute path to `~/.codex/config.toml`.
pub fn config_path() -> Result<PathBuf> {
    let home = dirs::home_dir()
        .ok_or_else(|| Error::Config("cannot determine home directory".to_string()))?;
    Ok(home.join(".codex").join("config.toml"))
}

/// Absolute path the dispatcher script lives at for a given project root.
pub fn dispatcher_path(project_root: &Path) -> PathBuf {
    project_root
        .join(STATE_DIR)
        .join(DISPATCHER_DIR)
        .join(DISPATCHER_FILE)
}

/// Render the canonical model and update `~/.codex/config.toml`.
pub fn write(canonical: &Canonical, project_root: &Path) -> Result<WriteReport> {
    let dest = config_path()?;
    detect_conflict(&dest)?;

    let mut report = WriteReport::default();
    let stop_commands = collect_stop_commands(canonical, &mut report);

    if stop_commands.is_empty() {
        // No Stop hooks → remove any managed block we previously wrote.
        if dest.exists() {
            let existing = fs::read_to_string(&dest)?;
            let updated = splice_block(&existing, None);
            if updated != existing {
                fs::write(&dest, updated)?;
            }
        }
        return Ok(report);
    }

    let dispatcher = dispatcher_path(project_root);
    write_dispatcher(&dispatcher, &stop_commands)?;

    let notify_line = format!(
        "notify = [\"bash\", \"{}\"]",
        escape_toml_string(&dispatcher.to_string_lossy())
    );
    let managed_block = format!("{BEGIN_MARKER}\n{notify_line}\n{END_MARKER}");

    let existing = if dest.exists() {
        fs::read_to_string(&dest)?
    } else {
        String::new()
    };
    let updated = splice_block(&existing, Some(&managed_block));

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&dest, updated)?;
    Ok(report)
}

/// Refuse-on-conflict: error out if `~/.codex/config.toml` has a `notify`
/// line outside the agentenv-managed sentinel block.
pub fn detect_conflict(dest: &Path) -> Result<()> {
    if !dest.exists() {
        return Ok(());
    }
    let raw = fs::read_to_string(dest)?;
    let unmanaged = strip_managed_block(&raw);
    if has_top_level_notify(&unmanaged) {
        return Err(Error::Config(format!(
            "{} already declares a top-level `notify` setting outside the agentenv-managed \
             block. agentenv refuses to overwrite. Either remove that line or set `source` to \
             a different target.",
            dest.display()
        )));
    }
    Ok(())
}

fn collect_stop_commands(canonical: &Canonical, report: &mut WriteReport) -> Vec<String> {
    let mut commands = Vec::new();
    for hook in &canonical.hooks {
        match &hook.event {
            Event::Common(CommonEvent::Stop) => {
                let Action::Command { command, .. } = &hook.action;
                commands.push(command.clone());
            },
            Event::Common(c) => {
                report.drops.push(format!(
                    "codex: dropping `{}` (only `Stop` maps to Codex notify)",
                    c.name()
                ));
            },
            Event::Native(n) => {
                report.drops.push(format!(
                    "codex: dropping native event `{}` from `{}` (Codex has no equivalent)",
                    n.native_event, n.source
                ));
            },
        }
    }
    commands
}

fn write_dispatcher(path: &Path, commands: &[String]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut body = String::new();
    body.push_str("#!/usr/bin/env bash\n");
    body.push_str("# Auto-generated by `agentenv sync`. Do not edit — re-run sync to refresh.\n");
    body.push_str("# Dispatches Codex notify events to every canonical Stop hook.\n");
    body.push_str("set -u\n");
    body.push_str("payload=\"${1-}\"\n");
    for cmd in commands {
        body.push_str("EVENT_JSON=\"$payload\" sh -c ");
        body.push_str(&shell_single_quote(cmd));
        body.push_str(" || true\n");
    }
    fs::write(path, body)?;
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(path, perms)?;
    }
    Ok(())
}

/// Splice the managed block in `existing`. If `new_block` is `Some`,
/// replace (or append) the block; if `None`, remove it entirely while
/// keeping every other line intact.
fn splice_block(existing: &str, new_block: Option<&str>) -> String {
    let begin = existing.find(BEGIN_MARKER);
    let end = existing.find(END_MARKER);

    let mut out = String::new();

    match (begin, end) {
        (Some(b), Some(e)) if e > b => {
            // Trim trailing newline before begin and leading newline after end
            // to avoid stacking blank lines.
            let before = existing[..b].trim_end_matches('\n');
            let after_idx = e + END_MARKER.len();
            let after = existing[after_idx..].trim_start_matches('\n');

            out.push_str(before);
            if !before.is_empty() && !out.ends_with('\n') {
                out.push('\n');
            }
            if let Some(block) = new_block {
                if !out.is_empty() && !out.ends_with("\n\n") {
                    if !out.ends_with('\n') {
                        out.push('\n');
                    }
                    out.push('\n');
                }
                out.push_str(block);
                if !block.ends_with('\n') {
                    out.push('\n');
                }
            }
            if !after.is_empty() {
                if !out.is_empty() && !out.ends_with("\n\n") {
                    if !out.ends_with('\n') {
                        out.push('\n');
                    }
                    out.push('\n');
                }
                out.push_str(after);
            }
        },
        _ => {
            out.push_str(existing);
            if let Some(block) = new_block {
                if !out.is_empty() && !out.ends_with('\n') {
                    out.push('\n');
                }
                if !out.is_empty() && !out.ends_with("\n\n") {
                    out.push('\n');
                }
                out.push_str(block);
                if !block.ends_with('\n') {
                    out.push('\n');
                }
            }
        },
    }
    out
}

/// Return `existing` with any agentenv-managed block stripped, so callers
/// can examine purely user-authored content.
fn strip_managed_block(existing: &str) -> String {
    splice_block(existing, None)
}

/// True if `text` contains a top-level `notify` assignment (key at column 0,
/// before any `[section]` header). This is a deliberately conservative
/// parser — TOML inside sections like `[mcp_servers]` is allowed to use
/// `notify` as a sub-key without triggering a conflict.
fn has_top_level_notify(text: &str) -> bool {
    let mut in_section = false;
    for line in text.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('[') {
            in_section = true;
            continue;
        }
        if !in_section && is_notify_assignment(trimmed) {
            return true;
        }
    }
    false
}

fn is_notify_assignment(line: &str) -> bool {
    let after_key = line.strip_prefix("notify").unwrap_or("");
    let rest = after_key.trim_start();
    rest.starts_with('=')
}

fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Wrap `s` in single quotes safely for inclusion in a bash `sh -c` argument.
fn shell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hooks::types::{Action, Canonical, CommonEvent, Event, Hook, Matcher};
    use tempfile::TempDir;

    fn cmd(s: &str) -> Action {
        Action::Command {
            command: s.to_string(),
            timeout_ms: None,
            cwd: None,
        }
    }

    fn stop(s: &str) -> Hook {
        Hook {
            event: Event::Common(CommonEvent::Stop),
            matcher: None,
            action: cmd(s),
        }
    }

    fn pretool(s: &str) -> Hook {
        Hook {
            event: Event::Common(CommonEvent::PreToolUse),
            matcher: Some(Matcher {
                tool: Some("Bash".to_string()),
            }),
            action: cmd(s),
        }
    }

    #[cfg(unix)]
    fn write_into(project: &Path, _home: &Path, canonical: &Canonical) -> Result<WriteReport> {
        // We can't easily redirect `dirs::home_dir()` per-test, so we exercise
        // the writer's pure pieces (splice + collect_stop_commands) directly
        // in most tests, and only use a real config file via override below.
        super::write(canonical, project)
    }

    /// Run with $HOME pointed at a temp dir for isolation. Returns the home
    /// path so callers can read the config back.
    ///
    /// Serializes against [`crate::hooks::HOME_LOCK`] — see its rustdoc for
    /// why we cannot use per-module locks.
    #[cfg(unix)]
    fn with_isolated_home<F: FnOnce(&Path) -> Result<WriteReport>>(
        f: F,
    ) -> (Result<WriteReport>, TempDir) {
        let _guard = crate::hooks::HOME_LOCK
            .lock()
            .unwrap_or_else(|p| p.into_inner());
        let home = TempDir::new().unwrap();
        let saved = std::env::var_os("HOME");
        std::env::set_var("HOME", home.path());
        let result = f(home.path());
        match saved {
            Some(v) => std::env::set_var("HOME", v),
            None => std::env::remove_var("HOME"),
        }
        (result, home)
    }

    #[test]
    fn collect_stop_picks_up_stops_and_drops_others() {
        let canonical = Canonical {
            source: "claude-code".to_string(),
            hooks: vec![stop("notify-done"), pretool("pre")],
        };
        let mut report = WriteReport::default();
        let commands = collect_stop_commands(&canonical, &mut report);
        assert_eq!(commands, vec!["notify-done".to_string()]);
        assert_eq!(report.drops.len(), 1);
        assert!(report.drops[0].contains("PreToolUse"));
    }

    #[test]
    fn splice_inserts_into_empty_file() {
        let out = splice_block("", Some("BLOCK"));
        assert_eq!(out, "BLOCK\n");
    }

    #[test]
    fn splice_appends_after_existing_content() {
        let existing = "model = \"x\"\n";
        let block = format!("{BEGIN_MARKER}\nnotify = [\"a\"]\n{END_MARKER}");
        let out = splice_block(existing, Some(&block));
        assert!(out.starts_with("model = \"x\""));
        assert!(out.contains(BEGIN_MARKER));
        assert!(out.contains("notify = [\"a\"]"));
    }

    #[test]
    fn splice_replaces_existing_managed_block_in_place() {
        let existing =
            format!("model = \"x\"\n\n{BEGIN_MARKER}\nold = 1\n{END_MARKER}\n\nother = 2\n");
        let block = format!("{BEGIN_MARKER}\nnotify = [\"new\"]\n{END_MARKER}");
        let out = splice_block(&existing, Some(&block));
        assert!(out.contains("model = \"x\""), "got: {out}");
        assert!(out.contains("notify = [\"new\"]"), "got: {out}");
        assert!(!out.contains("old = 1"), "got: {out}");
        assert!(out.contains("other = 2"), "got: {out}");
    }

    #[test]
    fn splice_removes_managed_block_when_passed_none() {
        let existing =
            format!("user = 1\n{BEGIN_MARKER}\nnotify = [\"x\"]\n{END_MARKER}\nuser2 = 2\n");
        let out = splice_block(&existing, None);
        assert!(out.contains("user = 1"));
        assert!(out.contains("user2 = 2"));
        assert!(!out.contains(BEGIN_MARKER));
        assert!(!out.contains("notify = [\"x\"]"));
    }

    #[test]
    fn has_top_level_notify_detects_unmanaged_assignment() {
        assert!(has_top_level_notify("notify = [\"x\"]\n"));
        assert!(has_top_level_notify("# comment\nnotify=[\"x\"]\n"));
        assert!(!has_top_level_notify(""));
        assert!(!has_top_level_notify("model = \"x\"\n"));
        // notify inside a section is OK (a sub-key, not the global hook).
        assert!(!has_top_level_notify("[mcp_servers]\nnotify = \"x\"\n"));
    }

    #[test]
    fn shell_quoting_handles_single_quote() {
        assert_eq!(shell_single_quote("echo 'hi'"), "'echo '\\''hi'\\'''");
    }

    // The tests below mutate `$HOME` to redirect `dirs::home_dir()` to a
    // temp dir. On Windows that resolver reads `%USERPROFILE%` instead, so
    // these tests would need a Windows-specific override. Codex CLI is
    // Unix-primary, so gate the HOME-mutating cases to Unix and keep the
    // pure logic tests (above) cross-platform.
    #[cfg(unix)]
    #[test]
    fn writes_dispatcher_and_notify_when_stop_present() {
        let project = TempDir::new().unwrap();
        let (result, home) = with_isolated_home(|_| {
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![stop("notify-a"), stop("notify-b")],
            };
            write_into(project.path(), Path::new("ignored"), &canonical)
        });
        let report = result.unwrap();
        assert!(report.drops.is_empty(), "drops: {:?}", report.drops);

        let dispatcher = dispatcher_path(project.path());
        let body = fs::read_to_string(&dispatcher).unwrap();
        assert!(body.contains("notify-a"));
        assert!(body.contains("notify-b"));

        let config = fs::read_to_string(home.path().join(".codex/config.toml")).unwrap();
        assert!(config.contains(BEGIN_MARKER));
        assert!(config.contains("notify"));
        assert!(config.contains(dispatcher.to_string_lossy().as_ref()));
    }

    #[cfg(unix)]
    #[test]
    fn write_with_no_stop_hooks_does_not_create_file_or_dispatcher() {
        let project = TempDir::new().unwrap();
        let (result, home) = with_isolated_home(|_| {
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![pretool("echo pre")],
            };
            write_into(project.path(), Path::new("ignored"), &canonical)
        });
        let report = result.unwrap();
        // PreToolUse should be dropped (only Stop maps).
        assert_eq!(report.drops.len(), 1);
        assert!(!dispatcher_path(project.path()).exists());
        assert!(!home.path().join(".codex/config.toml").exists());
    }

    #[cfg(unix)]
    #[test]
    fn refuses_user_authored_notify() {
        let project = TempDir::new().unwrap();
        let (result, _home) = with_isolated_home(|home_path| {
            let codex_dir = home_path.join(".codex");
            fs::create_dir_all(&codex_dir).unwrap();
            fs::write(codex_dir.join("config.toml"), "notify = [\"user\"]\n").unwrap();
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![stop("never-runs")],
            };
            write_into(project.path(), home_path, &canonical)
        });
        let err = result.unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("notify"), "got: {msg}");
        assert!(msg.contains("refuses"), "got: {msg}");
    }

    #[cfg(unix)]
    #[test]
    fn preserves_user_config_around_managed_block() {
        let project = TempDir::new().unwrap();
        let (result, home) = with_isolated_home(|home_path| {
            let codex_dir = home_path.join(".codex");
            fs::create_dir_all(&codex_dir).unwrap();
            fs::write(
                codex_dir.join("config.toml"),
                "model = \"o4-mini\"\n[mcp_servers]\nfoo = \"bar\"\n",
            )
            .unwrap();
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![stop("notify-done")],
            };
            write_into(project.path(), home_path, &canonical)
        });
        result.unwrap();
        let after = fs::read_to_string(home.path().join(".codex/config.toml")).unwrap();
        assert!(after.contains("model = \"o4-mini\""));
        assert!(after.contains("[mcp_servers]"));
        assert!(after.contains("foo = \"bar\""));
        assert!(after.contains(BEGIN_MARKER));
    }

    #[cfg(unix)]
    #[test]
    fn empty_stops_strips_existing_managed_block() {
        let project = TempDir::new().unwrap();
        let (_first, home) = with_isolated_home(|home_path| {
            // First sync: write notify block.
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![stop("once")],
            };
            let _ = write_into(project.path(), home_path, &canonical);

            // Second sync: no stops → block should be removed.
            let canonical = Canonical {
                source: "claude-code".to_string(),
                hooks: vec![],
            };
            write_into(project.path(), home_path, &canonical)
        });
        let after = fs::read_to_string(home.path().join(".codex/config.toml")).unwrap();
        assert!(!after.contains(BEGIN_MARKER), "after: {after}");
        assert!(!after.contains("notify"), "after: {after}");
    }
}
