//! Read and write `<project>/.agentenv/skills.canonical.yaml`.
//!
//! Mirrors [`crate::hooks::canonical_io`] — same auto-generated header, same
//! `.agentenv/` placement, idempotent `remove`. Users may inspect this file
//! to debug a sync but should not edit it: every `agentenv sync` regenerates
//! it from the configured `source` target.

use crate::error::{Error, Result};
use crate::skills::types::Canonical;
use crate::state::STATE_DIR;
use std::fs;
use std::path::{Path, PathBuf};

/// File name inside `.agentenv/` that holds the canonical artifact.
pub const CANONICAL_FILENAME: &str = "skills.canonical.yaml";

const HEADER: &str = "# Auto-generated by `agentenv sync`. Do not edit — re-run sync to refresh.\n";

/// Path the canonical artifact lives at for a given project root.
pub fn path(project_root: &Path) -> PathBuf {
    project_root.join(STATE_DIR).join(CANONICAL_FILENAME)
}

/// Serialize `canonical` to YAML and write it under
/// `<project_root>/.agentenv/skills.canonical.yaml`. Creates `.agentenv/`
/// if missing.
pub fn write(project_root: &Path, canonical: &Canonical) -> Result<PathBuf> {
    let dest = path(project_root);
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    let yaml = serde_yaml::to_string(canonical)?;
    let mut out = String::with_capacity(HEADER.len() + yaml.len());
    out.push_str(HEADER);
    out.push_str(&yaml);
    fs::write(&dest, out)?;
    Ok(dest)
}

/// Read and parse the canonical artifact, returning `Ok(None)` if it does
/// not exist (e.g. first sync on a fresh project).
pub fn read(project_root: &Path) -> Result<Option<Canonical>> {
    let path = path(project_root);
    if !path.exists() {
        return Ok(None);
    }
    let content = fs::read_to_string(&path)?;
    let parsed = serde_yaml::from_str(&content).map_err(|err| {
        Error::Config(format!(
            "invalid canonical skills file {}: {err}",
            path.display()
        ))
    })?;
    Ok(Some(parsed))
}

/// Delete the canonical artifact if present. Idempotent.
pub fn remove(project_root: &Path) -> Result<()> {
    let path = path(project_root);
    if path.exists() {
        fs::remove_file(&path)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::types::CanonicalSkill;
    use tempfile::TempDir;

    fn sample() -> Canonical {
        let mut frontmatter = serde_yaml::Mapping::new();
        frontmatter.insert(
            serde_yaml::Value::String("name".to_string()),
            serde_yaml::Value::String("hello".to_string()),
        );
        Canonical {
            source: "claude-code".to_string(),
            skills: vec![CanonicalSkill {
                name: "hello".to_string(),
                frontmatter,
                body: "# Hello\n".to_string(),
                sidecars: vec![],
                source_dir: PathBuf::from("/tmp/skills/hello"),
            }],
        }
    }

    #[test]
    fn write_then_read_round_trips_persisted_fields() {
        let project = TempDir::new().unwrap();
        let original = sample();
        write(project.path(), &original).unwrap();
        let loaded = read(project.path()).unwrap().unwrap();
        assert_eq!(loaded.source, original.source);
        assert_eq!(loaded.skills.len(), 1);
        assert_eq!(loaded.skills[0].name, original.skills[0].name);
        assert_eq!(loaded.skills[0].frontmatter, original.skills[0].frontmatter);
        assert_eq!(loaded.skills[0].body, original.skills[0].body);
        // `source_dir` is `#[serde(skip)]`, so it does not persist.
        assert_eq!(loaded.skills[0].source_dir, PathBuf::new());
    }

    #[test]
    fn read_missing_file_returns_none() {
        let project = TempDir::new().unwrap();
        assert!(read(project.path()).unwrap().is_none());
    }

    #[test]
    fn write_includes_do_not_edit_header() {
        let project = TempDir::new().unwrap();
        write(project.path(), &sample()).unwrap();
        let raw = fs::read_to_string(path(project.path())).unwrap();
        assert!(raw.starts_with("# Auto-generated"));
    }

    #[test]
    fn remove_is_idempotent() {
        let project = TempDir::new().unwrap();
        remove(project.path()).unwrap();
        write(project.path(), &sample()).unwrap();
        remove(project.path()).unwrap();
        assert!(!path(project.path()).exists());
    }
}
